import numpy as np

# glicko variables
C = np.sqrt((350**2 - 200**2)/80)

MAX_EAGERNESS = 5
MAX_DODGE = 0.04

# goblin creation normal distributions
# (mean, std, lower_bound, upper_bound)
STAT_DISTRIBUTIONS = {"hp":             (40, 12, 20, 60), 
                      "strength":       (20, 5, 10, 30), 
                      "cooldown":       (5, 2, 1, 9), 
                      "guard":          (0.5, 0.25, 0, 0.9),
                      "lr":             (0.01, 0.005, 0.001, 0.03),
                      "funding":        (100, 100, 5, 300),
                      }

COMBAT_MULTIPLIERS = {"vanilla":    1/4,
                      "guard":      1/10, #1/8
                      "guardbreak": 1/3,
                      "parry":      1/2,
                      "crit":       4,
                      }


## Name creation variables
NUMERALS = ["", "I", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"]

PLACEHOLDER_NAMES = [
    "Snickerdoodle",
    "Grumbleflap",
    "Wartbucket",
    "Fizzlepop",
    "Squidney",
    "Bumblegut",
    "Toadfluff",
    "Moldysnot",
    "Rumblebelly",
    "Gobsmack",
    "Snaggletooth",
    "Noodlewhisker",
    "Crankyboots",
    "Picklefingers",
    "Squeakums",
    "Gobbledegook",
    "Mudwobble",
    "Jellybelch",
    "Snotnoodle",
    "Froggleflop",
    "Gobbledorf",
    "Noodlegrump",
    "Bogbottom",
    "Gigglesnort",
    "Wobblechomp",
    "Munchkin",
    "Fuzzywump",
    "Gobblenose",
    "Gigglefizz",
    "Sneezewort",
    "Stinkerbelle",
    "Moldysprocket",
    "Bumblewhisk",
    "Wartnibbler",
    "Snickerdust",
    "Gobbleflap",
    "Fizzlefuzz",
    "Gurglebum",
    "Snotwhistle",
    "Grumbletooth",
    "Squeezle",
    "Noodlebop",
    "Toadstool",
    "Munchkinella",
    "Rumblegurgle",
    "Bogsnuggle",
    "Picklegrin",
    "Gigglewobble",
    "Sneezesprocket",
    "Wobblewrench",
    "Froggleblip",
    "Jellybelly",
    "Squidgums",
    "Giggledrip",
    "Noodlepluck",
    "Gobblenibble",
    "Mudfizzle",
    "Bumbleburp",
    "Squeakernose",
    "Chucklebump"
]

TOURN_TYPES = [
    "Championship",
    "Classic",
    "Invitational",
    "Showdown",
    "Showcase",
    "Challenge",
    "Clash",
    "Derby",
    "Championship Series",
    "Grand Prix",
    "Rumble",
    "Face-Off",
    "Gauntlet",
    "Melee",
    "Fest",
    "Carnival",
    "Gala",
    "Summit",
    "Extravaganza",
]
# random mix of names and places in the uk from a generative model
TOURN_TITLES = [
    "Karen",
    "Linda",
    "Susan",
    "Deborah",
    "Nancy",
    "Donna",
    "Cynthia",
    "Pamela",
    "Sharon",
    "Teresa",
    "Cheryl",
    "Julie",
    "Christine",
    "Catherine",
    "Barbara",
    "Patricia",
    "Mary",
    "Jennifer",
    "Elizabeth",
    "Dorothy",
    "John",
    "Michael",
    "David",
    "James",
    "Robert",
    "William",
    "Richard",
    "Thomas",
    "Joseph",
    "Charles",
    "Steven",
    "Kenneth",
    "Paul",
    "Mark",
    "Daniel",
    "George",
    "Brian",
    "Jeffrey",
    "Scott",
    "Kevin",
    "Middlesbrough",
    "Blackpool",
    "Rhyl",
    "Grimsby",
    "Rotherham",
    "Luton",
    "Port Talbot",
    "Hull",
    "Stoke-on-Trent",
    "Croydon",
    "Bradford",
    "Dagenham",
    "Preston",
    "Wolverhampton",
    "Sunderland",
    "Scunthorpe",
    "Swindon",
    "Doncaster",
    "Wigan",
    "Birmingham",
    "Newcastle upon Tyne",
    "Manchester",
    "Liverpool",
    "Leeds",
    "Glasgow",
    "Bristol",
    "Sheffield",
    "Nottingham",
    "Cardiff",
    "Edinburgh",
    "Leicester",
    "Southampton",
    "Brighton",
    "Cambridge",
    "York",
    "Bath",
    "Stratford-upon-Avon",
    "Canterbury",
    "Durham",
    "Windsor",
    "Oxford",
    "St. Albans",
    "Exeter",
    "Bournemouth",
    "Harrogate",
]
